"""add document provenance

Revision ID: 20260812_0002
Revises: 20260812_0001
Create Date: 2026-08-12 22:16:27.612781
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260812_0002"
down_revision: str | None = "20260812_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "stored",
                "processing",
                "processed",
                "failed",
                name="documentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("parser_version", sa.String(length=50), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'failed' AND failure_code IS NOT NULL) OR "
            "(status <> 'failed' AND failure_code IS NULL)",
            name=op.f("ck_source_documents_failure_code_status"),
        ),
        sa.CheckConstraint(
            "media_type IN ('application/pdf', "
            "'application/vnd.openxmlformats-officedocument.wordprocessingml.document', "
            "'text/plain')",
            name=op.f("ck_source_documents_supported_media_type"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'stored', 'processing', 'processed', 'failed')",
            name=op.f("ck_source_documents_supported_status"),
        ),
        sa.CheckConstraint(
            "sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_source_documents_sha256_format"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_source_documents_positive_size")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_source_documents_storage_key")),
    )
    op.create_index("ix_source_documents_sha256", "source_documents", ["sha256"], unique=False)
    op.create_table(
        "evidence_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("document", "user_statement", name="evidencesourcetype", native_enum=False),
            nullable=False,
        ),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source_type = 'document' AND source_document_id IS NOT NULL) OR "
            "(source_type = 'user_statement' AND source_document_id IS NULL)",
            name=op.f("ck_evidence_sources_source_document_type"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_evidence_sources_source_document_id_source_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_sources")),
    )
    op.create_index(
        op.f("ix_evidence_sources_source_document_id"),
        "evidence_sources",
        ["source_document_id"],
        unique=False,
    )
    op.create_table(
        "evidence_spans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("evidence_source_id", sa.Uuid(), nullable=False),
        sa.Column("quoted_text", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(start_offset IS NULL AND end_offset IS NULL) OR "
            "(start_offset >= 0 AND end_offset > start_offset)",
            name=op.f("ck_evidence_spans_valid_offsets"),
        ),
        sa.CheckConstraint(
            "length(quoted_text) > 0", name=op.f("ck_evidence_spans_quoted_text_present")
        ),
        sa.CheckConstraint(
            "sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_evidence_spans_sha256_format"),
        ),
        sa.CheckConstraint(
            "page_number IS NULL OR page_number > 0", name=op.f("ck_evidence_spans_positive_page")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_source_id"],
            ["evidence_sources.id"],
            name=op.f("fk_evidence_spans_evidence_source_id_evidence_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_spans")),
    )
    op.create_index(
        op.f("ix_evidence_spans_evidence_source_id"),
        "evidence_spans",
        ["evidence_source_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_spans_evidence_source_id"), table_name="evidence_spans")
    op.drop_table("evidence_spans")
    op.drop_index(op.f("ix_evidence_sources_source_document_id"), table_name="evidence_sources")
    op.drop_table("evidence_sources")
    op.drop_index("ix_source_documents_sha256", table_name="source_documents")
    op.drop_table("source_documents")
    # ### end Alembic commands ###
